name: Release build

on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Generate Keystore file from Github Secrets
      run: |
        echo "${{ secrets.APP_KEYSTORE_BASE64 }}" > ./keystore.b64
        base64 -d -i ./keystore.b64 > ./${{ secrets.APP_KEY_FILE }}
        cp ./${{ secrets.APP_KEY_FILE }} ./app/${{ secrets.APP_KEY_FILE }}
      shell: bash
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      run: |
        echo ${{ steps.vars.outputs.tag }}
    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.3
      with:
        gradlePath: app/build.gradle.kts
        versionCode: ${{github.run_number}}
        versionName: ${{steps.vars.outputs.tag}}

    - name: Build Release APK
      run: |
        bash ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=${{ secrets.APP_KEY_FILE }} \
          -Pandroid.injected.signing.store.password=${{ secrets.APP_KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.APP_KEYSTORE_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.APP_KEY_PASSWORD }} \
          --stacktrace
      shell: bash
    - name: Upload artifact Release APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk
    - name: Download APK
      uses: actions/download-artifact@v4
      with:
        name: apk
    - name: Upload Release APK
      id: upload_release_asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        upload_url: ${{ github.event.release.url }}
        asset_path: ./apk/app-release.apk
        asset_name: SampleAndroidApplication.apk
        asset_content_type: application/vnd.android.package-archive
